---
# Set up cockpit
- name: Install nginx
  yum:
    name:
      - cockpit-ws
      - cockpit-bridge
      - cockpit-system
    state: latest

- name: Update local firewall for serving cockpit pages
  firewalld:
    port: "8080/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: Enable and start cockpit
  service:
    name: cockpit.socket
    state: started
    enabled: yes
