---
- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Copy sample NGINX configuration
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart NGINX after configuration change

- name: Copy sample NGINX index.html
  template:
    src: index_html.j2
    dest: /usr/share/nginx/html/index.html
  notify: Restart NGINX after configuration change

- name: Update local firewall for serving web pages
  firewalld:
    port: "80/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: Enable and start NGINX
  service:
    name: nginx
    state: started
    enabled: yes
